<a href="https://colab.research.google.com/github/charlie-aashutosh/Tensorflow-2.0/blob/master/Getting_started_with_TF2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow-gpu==2.0.0-alpha0

In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
tf.__version__

'2.2.0'

In [4]:
#Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [5]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [6]:
#Getting shape of a tensor
tensor_20.shape

TensorShape([2, 2])

In [7]:
#Getting values straight from a TensorFlow constant to numpy - withut sesion
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [8]:
#We are able to convert a numpy matrix back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,  4], [32, 51]])

In [9]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [10]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

In [11]:
#Operations with constants/tensors
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [13]:
#addition of tensor and scelar
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [14]:
#multiplication of tensor and scelar
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [15]:
#Squaring all numbers in a tensorflow tensor object
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [16]:
#Square root of all numbers in a tensorflow tensor object
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [18]:
#dot product of tensor and scelar
np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

In [19]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [20]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [21]:
#changing specific value from tensorflow variable
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [22]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [23]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

In [24]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [25]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

In [26]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [27]:
#How to iterate through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


In [28]:
#handling devices in tensorlflow 2.0
with tf.device("/cpu:0"):
    tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [29]:
tf_string_array.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [31]:
if tf.test.is_gpu_available():
    with tf.device("/gpu:0"):
        tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
    print(tf_string_array.device)

/job:localhost/replica:0/task:0/device:CPU:0
